dist: trusty
sudo: false

language: node_js

node_js:
  - "node"

branches:
  only:
    - master
    - /^\d.\d+-release$/

before_script:
  - npm install -g grunt-cli
  - cp grunt.json.dist grunt.json

script:
  - grunt build

notifications:
  email: false
  slack:
    secure: qlhuBuOJvERGuXGKtGQC4IRVrRelfaCwRPRw7EwWTwF9aQqB7UD9JEOwd2yPAXh4fGOkZbzmn4dKrJlClkoRvyg7RSJ8ctbWC1yti/w6BJKpydeILC5+Ep2cJyd8TLL0nzTASKQrrrwsAba3archmIaOCZxQyJw99nSDnE4Pb751u4m9GLomLluE0FT4jUs/nx+qFLl2DjEJGnnu2o1FER5/goksJpJW5wGFsQnA8TDodQN4YaXsOs5e504WbfRfgTJEzMhyWheD1JrPdLY9i4I8HzU+Vz9vNaWlSSChPg/kciNCIuM2FUvQAxpIiKf66Xwwutl+iR8bzvi1GEG4WPPr7v00xFZIBeHThrm8NbDJyHfGGFLEUp0cFSA4RMmDgyonIjUgAMI83XseyRViTkcpykQ7mtRWiR/M+83w2BsfYovQnIBEXZ9rMJTkdgi/utNY54ajLJyngmdhpvS5vMsFQ2Bamc5OtETsE51DIS0ZEzGwANDX69YjebQkDMWX3t50BK92m463i6obajtCb4eDb4+lPH3FuzLbkZL5A5iPNUj5rZw8P3SVLxsbhyMUvqOkxxCGqQt5C5AAeO1VCa0u60kNAZogvanpIn61lB+bMlvqklDjDo6QkcCjcs10LwV5DyQU35/50CTzntD2eTn3gVdbWuI4cBQRdJiwHzA=
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
