dist: xenial

language: node_js

node_js:
  - "node"

cache:
  npm: false

addons:
  apt:
    packages:
      - libgconf-2-4

matrix:
  include:
    - env: RUN_TESTS="yes"
    - env: RUN_BUILD="yes"

branches:
  only:
    - master
    - /^\d.\d+$/

before_script:
  - cp .env.dist .env

script:
  - |
    if [ "$RUN_TESTS" = "yes" ] ; then
      yarn run ci
    fi

  - |
    if [ "$RUN_BUILD" = "yes" ] ; then
      yarn run build
    fi

notifications:
  email: false
  slack:
    rooms:
      - secure: "YYaXkGLCwlmjPrfqC+sAuBnxVIrhUneoKzEUHKYN0hWJ7YMBbOUrvEGXcr7/XgqQr9rsq/Gr9iZRYdv08LkU+sv4y/dLyYjcpZdfWoputxFlp+KKaczKxtBX1WwCiI4vanYQDxpLcJEH8G9b0TXjLqKXFLZ/alfxVo0YiNA7J8N1k6KZyRrIaSyV+0P2VD+i3O2NpS/m0Rs6LitjiZMe4V5i6aWfMwTemwQcUpIs8TNJtmKKbQAHjfMAGykS6AW6qk1bqXz83SL/ZOqc4y1vefh87slbK2/yEo0OdqPgipsUww77rTDAHydiH/VqZV2q/rfgTC5/kY7wuhHbDxcHLJtymfRpzyyo5WIemPdhCvExz4Be+k80lkHuXseNhBfJxOGOuqpzPXi5/5WuQ5S9IqTlGNWIThWwM3WVc76NUyngUkfwkWg65oatLECOA3HhBjzfQL2vOO7bSzqwDW24TWwN2RU8H+vtRzRzTr2KltgxP12vz45BRtlOZi8c5B7Zd0UqCRSS2AGL/fBB2nV/yKzdxEW9qnzSlDOM6/e1aVl+csr3lHzasUPa0pDBcE48DRfl/dS3AUwXiTZ6/5MtGRd4nC9dYQqyR5fvsShIbaZL3Som/43IDD6SbKhGnFT7+BR1dte5kBWqBKL6QVuDuyTB34k/zZbVt2csSLwVfDQ="
    on_success: change
    on_failure: always
    on_pull_requests: false

git:
  depth: 1
