assets:
    packages:
        ngcb_css:
            base_path: '/bundles/netgencontentbrowserui/css'
            version: '%netgen_content_browser.asset.version%'
            version_format: '%%s?%%s'
        ngcb_js:
            base_path: '/bundles/netgencontentbrowserui/js'
            version: '%netgen_content_browser.asset.version%'
            version_format: '%%s?%%s'
        ngcb:
            base_path: '/bundles/netgencontentbrowserui'
            version: '%netgen_content_browser.asset.version%'
            version_format: '%%s?%%s'
